# Generated by Django 4.1.2 on 2022-10-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_category_name_en_color_name_en_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(default='', null=True, related_name='products', to='shop.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(default='', null=True, related_name='products', to='shop.size'),
        ),
    ]
