# Generated by Django 4.1.2 on 2022-10-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_colors_alter_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability_in',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(default='', null=True, related_name='products', to='shop.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(default='', null=True, related_name='products', to='shop.size'),
        ),
    ]
