# Generated by Django 4.1.2 on 2022-10-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_availability_in_alter_product_colors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, default='', related_name='products', to='shop.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, default='', related_name='products', to='shop.size'),
        ),
    ]
