# Generated by Django 4.1.2 on 2022-10-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_product_colors_alter_product_sizes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='colors',
            new_name='color',
        ),
    ]
